// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoTFo-ThNPuqOYEWM6Zs_RKu2IT6EKjH8',
    appId: '1:340613199565:android:bc1990dbb19b2489c91b84',
    messagingSenderId: '340613199565',
    projectId: 'q-w-c-75337',
    databaseURL: 'https://q-w-c-75337-default-rtdb.firebaseio.com',
    storageBucket: 'q-w-c-75337.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnjj4t-SvMj77TWtDeYyGl1stR4KjFLRg',
    appId: '1:340613199565:ios:1c5fda61a417c9ccc91b84',
    messagingSenderId: '340613199565',
    projectId: 'q-w-c-75337',
    databaseURL: 'https://q-w-c-75337-default-rtdb.firebaseio.com',
    storageBucket: 'q-w-c-75337.appspot.com',
    iosClientId: '340613199565-5qu437dv6orgnh1rt6e01egc2mvu475s.apps.googleusercontent.com',
    iosBundleId: 'com.miastudiosinc.qwc',
  );
}
